### ISSUE TITLE
Competent Speaker of the House Badge

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#55]
GIVEN | WHEN | THEN
-- | -- | --
Player doesn’t have a “Competent Speaker of the House” badge in the current season | Approver approves the Special Quest | Player receives a “Competent Speaker of the House” badge AND a raffle ticket for the current month

**Comment by edanga** [comment]
Initial ETA;
Development: 8 hours
Code Review: 2 hours
Testing: 2 hours

**Comment by JoanBaraquiel** [comment]
1. Player submit a special quest
2. Approver approves the special quest
3. Player gets 20 XP 

Instead of getting a "Competent Speaker of the House Badge", I got another "Good work" Badge.

![image](https://user-images.githubusercontent.com/51430213/65928502-c53a3480-e430-11e9-8a17-21990f464cc7.png)

**Comment by JoanBaraquiel** [comment]
I got now the "Competent Speaker of the House Badge" 

**
![image](https://user-images.githubusercontent.com/51430213/66100264-d0ca5e80-e5dc-11e9-92a6-c9fb742fe939.png)
**
